umbraco/Umbraco.UI

src/components/uui-breadcrumbs/uui-breadcrumb-item.element.ts, src/components/uui-breadcrumbs/uui-breadcrumb-item.test.ts, src/components/uui-breadcrumbs/uui-breadcrumbs.element.ts, src/components/uui-breadcrumbs/uui-breadcrumbs.test.ts, src/components/uui-loader/uui-loader.element.ts, src/components/uui-table/uui-table.element.ts, src/components/uui-table/uui-table.test.ts
Cleanup and tests for:
- Breadcrumbs, BreadcrumbItem.
- Loader
- Table
=> Components cleanup and tests

packages/uui-box/lib/uui-box.element.ts, packages/uui-table/lib/uui-table-cell.element.ts, packages/uui-table/lib/uui-table-row.element.ts
increase spacing in the table and box
=> Bump spacing for table and box

packages/uui-caret/lib/uui-caret.story.ts
=> remove console log

packages/uui-avatar-group/README.md, packages/uui-avatar/README.md, packages/uui-badge/README.md, packages/uui-base/README.md, packages/uui-box/README.md, packages/uui-breadcrumbs/README.md, packages/uui-button-group/README.md, packages/uui-button/README.md, packages/uui-caret/README.md, packages/uui-checkbox/README.md, packages/uui-input/README.md, packages/uui-keyboard-shortcut/README.md, packages/uui-loader-bar/README.md, packages/uui-loader-circle/README.md, packages/uui-loader/README.md, packages/uui-menu-item/README.md, packages/uui-radio/README.md, packages/uui-slider/README.md, packages/uui-table/README.md, packages/uui-tabs/README.md, packages/uui-tag/README.md, packages/uui-toggle/README.md, packages/uui/README.md
Updates links to npm packages.
=> Update links to npm packages

package-lock.json, packages/uui-select/package.json, packages/uui-textarea/package.json
Bump base dependency in uui-textarea
It should be the latest one
=> chore: bump uui-base in uui-textarea

.storybook/main.js, packages/uui-avatar-group/lib/uui-avatar-group.story.ts, packages/uui-avatar/lib/uui-avatar.element.ts, packages/uui-avatar/lib/uui-avatar.story.ts, packages/uui-badge/lib/uui-badge.element.ts, packages/uui-badge/lib/uui-badge.story.ts, packages/uui-badge/lib/uui-badge.test.ts, packages/uui-base/lib/animations/uui-blink.ts, packages/uui-base/lib/animations/uui-pulse.ts, packages/uui-base/lib/mixins/LabelMixin.ts, packages/uui-base/lib/mixins/SelectableMixin.ts, packages/uui-base/lib/types/Size.ts, packages/uui-base/lib/types/index.ts, packages/uui-box/lib/uui-box.story.ts, packages/uui-breadcrumbs/lib/uui-breadcrumbs.story.ts, packages/uui-button/lib/uui-button.element.ts, packages/uui-button/lib/uui-button.story.ts, packages/uui-button/lib/uui-button.test.ts, packages/uui-icon/lib/uui-icon.story.ts, packages/uui-pagination/lib/uui-pagination.element.ts, packages/uui-pagination/lib/uui-pagination.test.ts, packages/uui-table/lib/uui-table.story.ts, packages/uui-tag/lib/uui-tag.element.ts, packages/uui-tag/lib/uui-tag.story.ts, packages/uui-tag/lib/uui-tag.test.ts, src/components/uui-select-option/uui-select-option.element.ts, storyhelpers/UmbracoWordGenerator.ts
=> General improved sizing options and others minor corrections

packages/uui-slider/lib/UUISliderEvents.ts, packages/uui-slider/lib/uui-slider.element.ts, packages/uui-slider/lib/uui-slider.story.ts, packages/uui-slider/lib/uui-slider.test.ts
=> Clean up and refactor slide component

packages/uui-slider/README.md
=> Fix typo in uui-slider image badge

packages/uui-css/lib/custom-properties.story.ts
For better performance, in this PR the event lister needed to copy custom properties or their values to the clipboard was moved to `uui-table`. That way we have only one listener instead of many.
=> Refactor css custom properties story

packages/uui-toast-notification-container/lib/uui-toast-notification-container.test.ts, packages/uui-toast-notification/lib/uui-toast-notification.element.ts, packages/uui-toast-notification/lib/uui-toast-notification.test.ts
adding --uui-toast-notification-animation-duration custom prop for toast notification. Testing it and using it for other tests.
=> use --uui-toast-notification-animation-duration for transition duration

package-lock.json, packages/uui-menu-item/lib/uui-menu-item.element.ts, packages/uui-menu-item/lib/uui-menu-item.story.ts, packages/uui-menu-item/lib/uui-menu-item.test.ts, packages/uui-pagination/lib/uui-pagination.element.ts
Adding href and target property to menu item.
this is rendering the anchor tag when href is present.
=> Support href and render a anchor tag

packages/uui-base/lib/mixins/ActiveMixin.ts, packages/uui-base/lib/mixins/LabelMixin.ts, packages/uui-button-inline-create/lib/uui-button-inline-create.element.ts, packages/uui-button/lib/uui-button.element.ts, packages/uui-menu-item/lib/uui-menu-item.element.ts, packages/uui-menu-item/lib/uui-menu-item.story.ts, packages/uui-menu-item/lib/uui-menu-item.test.ts, packages/uui-symbol-expand/lib/uui-symbol-expand.element.ts, packages/uui-symbol-sort/lib/uui-symbol-sort.element.ts, packages/uui-tabs/lib/uui-tab.element.ts
* Improves the Storybook stories for uui-menu-item
* Adds inheritance docs from mixins
* Adds missing documentation for certain properties and slots
Fixes [AB#17615](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17615)
=> uui-menu-item docs and tests

packages/uui-avatar-group/lib/uui-avatar-group.story.ts, packages/uui-avatar/lib/uui-avatar.story.ts
Updates the Avatar & Avatar Group documentation so that the code samples are more useful.
Allowing me to copy them and get the same result as the displayed story.
=> Tidies up docs for Avatar & Avatar Group

packages/uui-badge/lib/uui-badge.story.ts
Improve examples/docs for uui-badge component
=> Improving docs for badge

packages/uui-base/lib/mixins/SelectableMixin.ts, packages/uui-card-content-node/lib/uui-card-content-node.element.ts, packages/uui-card-media/lib/uui-card-media.element.ts, packages/uui-card-user/lib/uui-card-user.element.ts, packages/uui-card/lib/uui-card.element.ts
This also fixes a mixup of events that was forgotten
Fixes [AB#18369](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/18369)
=> docs(storybook): move events to SelectableMixin base class

package-lock.json, packages/uui-box/README.md, packages/uui-box/lib/uui-box.element.ts, packages/uui-box/lib/uui-box.story.ts, packages/uui-box/lib/uui-box.test.ts, packages/uui-box/package.json, packages/uui-box/tsconfig.json, packages/uui-button/lib/uui-button.element.ts, packages/uui-table/lib/uui-table.story.ts
Changing slots of uui-box to provide a simpler Developer Experience and to match dialog-layout.
As well this fixes styling issue of https://github.com/umbraco/Umbraco.UI/issues/164
fixes https://github.com/umbraco/Umbraco.UI/issues/164
=> Updated slots of uui-box, simpler DX

packages/uui-action-bar/lib/uui-action-bar.story.ts, packages/uui-avatar-group/lib/uui-avatar-group.story.ts, packages/uui-avatar/lib/uui-avatar.story.ts, packages/uui-breadcrumbs/lib/uui-breadcrumbs.story.ts, packages/uui-button-group/lib/uui-button-group.story.ts, packages/uui-button-inline-create/lib/uui-button-inline-create.element.ts, packages/uui-button-inline-create/lib/uui-button-inline-create.story.ts, packages/uui-card-content-node/lib/uui-card-content-node.story.ts, packages/uui-card-media/lib/uui-card-media.story.ts, packages/uui-card-user/lib/uui-card-user.story.ts, packages/uui-caret/lib/uui-caret.element.ts, packages/uui-icon-registry/lib/uui-icon-registry.story.ts, packages/uui-icon/lib/uui-icon.story.ts, packages/uui-loader-bar/lib/uui-loader-bar.story.ts, packages/uui-loader-circle/lib/uui-loader-circle.story.ts, packages/uui-loader/lib/uui-loader.story.ts, packages/uui-radio/lib/uui-radio.story.ts, packages/uui-tag/lib/uui-tag.story.ts, packages/uui-toast-notification/lib/uui-toast-notification.story.ts
A round of clean up in storybook. This PR is the first round with the vacuum cleaner. More to come later :)
I have made updates to the following stories:
* action-bar
* avatar-group
* avatar
* breadcrumbs
* button-group
* button-inline-create
* card-content-node
* card-media
* card-user
* caret
* Icon-registry
* loader-bar
* loader
* radio
* tag
* toast notification
=> Storybook Spring Cleaning Round 1

packages/uui-css/README.md, packages/uui-css/lib/uui-css.story.ts
Adds documentation about how you import and use the package
=> Added uui-css documentation

packages/uui-symbol-expand/lib/uui-symbol-expand.element.ts, packages/uui-symbol-sort/lib/uui-symbol-sort.element.ts
Minor spelling (meaning) change for issue spotted during workshop
=> Change weather to whether

packages/uui-table/lib/uui-table-row.element.ts
Fixes https://github.com/umbraco/Umbraco.UI/issues/237
=> Stop using outline for selection border

packages/uui-css/lib/custom-properties.story.ts
Adds following properties to storybook:
--uui-color-default-*
--uui-color-interactive
--uui-color-interactive-emphasis
Also adds documentation to the interface color properties.
Fixes #240
=> Add missing color properties and documentation to storybook

packages/uui-base/lib/animations/uui-blink.ts, packages/uui-button-inline-create/lib/uui-button-inline-create.element.ts, packages/uui-button-inline-create/lib/uui-button-inline-create.story.ts
corrected margins to make button center correctly.
=> Fix: uui-button-inline-create correction of margins for centering of the button

packages/uui-toast-notification/lib/uui-toast-notification.story.ts
This PR sets args in the `uui-notification` story so they reflect the type of the property
=> Fix uui-toast-notification story args

packages/uui-button/lib/uui-button.element.ts, packages/uui-button/lib/uui-button.story.ts
Added padding variable to button top/bottom
The padding is removed on compact buttons
Added story for multi line buttons
=> fixed padding and added multiline story

packages/uui-base/lib/mixins/LabelMixin.ts, packages/uui-form-layout-item/lib/uui-form-layout-item.story.ts, packages/uui-input/lib/uui-input.element.ts
Add labels to fix Storybook warnings
=> Add labels to fix accessibility warnings

.storybook/main.js, .storybook/preview.js
Enables Story Store v7 that loads stories on-demand, which makes storybook startup much faster.
=> added story store v7

packages/uui-button-group/lib/uui-button-group.element.ts, packages/uui-button-group/lib/uui-button-group.story.ts, packages/uui-popover/lib/uui-popover.element.ts
This PR makes the popover component display properly when used inside the button group. 
The reason behind is is to be able to have a dropdown menu in the button group.
=> Make popover work nicely in the button group

packages/uui-card-media/lib/uui-card-media.element.ts, packages/uui-card-media/lib/uui-card-media.story.ts
Fixed wrong css variables for disabled media card footer.
Added secondary look to remove button
=> FIXES:#295 - Missing media card disabled footer and action button backgrounds 

packages/uui-radio/lib/uui-radio.element.ts, packages/uui-radio/lib/uui-radio.story.ts
When building something using the UUI library components for a form I am building that has very long answers and span multiple lines. The radio button circle becomes more of an oval.
Makes it look normal again
=> Bugfix - UUI Radiobutton Circle is malformed on multiple lines

packages/uui-button/lib/uui-button.element.ts
Fixes state styling in uui-button
=> uui-button: Fixes styling on success and failed state

packages/uui-button-inline-create/lib/uui-button-inline-create.story.ts
Makes the stories more clear by adding list items and borders.
=> Improve uui-inline-button-create stories

packages/uui-button-inline-create/lib/uui-button-inline-create.element.ts
=> uui-inline-button-create: fix for the border color on horizontal

package-lock.json, package.json, tsconfig.json
=> build(deps-dev): update typescript to 4.8.3

packages/uui-combobox/lib/uui-combobox.element.ts
Adds an alternate combobox view for phone users
Fixes #307
=> uui-combobox: optimizations for small resolutions

packages/uui-input-password/lib/uui-input-password.element.ts
=> uui-input-password sets spellcheck to false

packages/uui-combobox-list/lib/UUIComboboxListEvent.ts, packages/uui-combobox-list/lib/uui-combobox-list.element.ts, packages/uui-combobox/lib/uui-combobox-async-options-example.ts, packages/uui-combobox/lib/uui-combobox.element.ts, packages/uui-combobox/lib/uui-combobox.story.ts
Fixes #386 
Adds an slot-changed event to the combobox-list that fires when children(options) of the component changes. The combobx listens for this event and correctly updates the combobox lists' value and its own display value.
Also adds the async options example story that @julczka provided, and uncommented (and testing) the async data example story already present in the codebase.
Follow whats described in issue #386
=> Combobox not working with async options

packages/uui-input/lib/uui-input.element.ts
Adds `-webkit-text-fill-color` styling to support safari
=> Disabled input not displayed properly in Safari

packages/uui-modal/lib/uui-modal-sidebar.element.ts
Adds missing size property to sidebar
=> Modals - add size property to sidebar

packages/uui-css/lib/uui-text.css
Adds default styling to the a tag
=> added default styling to a tag

packages/uui-css/lib/guidelines.story.ts, packages/uui-dialog/lib/uui-dialog.element.ts, packages/uui-dialog/lib/uui-dialog.story.ts
Guide to suit developers/designs making friendly dialogs
=> dialog guideline

packages/uui-base/lib/mixins/SelectableMixin.ts, packages/uui-card/lib/uui-card.element.ts, packages/uui-css/lib/guidelines.story.ts
This was using the wrong string, which resulted in no update when setting this like a property internally. example when extending the element.
=> correct requestUpdate call

packages/uui-card/lib/uui-card.element.ts, packages/uui-card/lib/uui-card.story.ts
Adding a default slot to the uui-card so it can be utilized without being extended.
=> default slot + story

packages/uui-css/lib/custom-properties.css, packages/uui-css/lib/custom-properties/fonts.css
Task 30220
Exports the font family in a variable as `--uui-font-family`
Welcoming any suggestions to other naming of the variable.
=> export font family in variable

packages/uui-css/lib/custom-properties/colors.css, packages/uui-css/lib/custom-properties/palette.css
=> correct green colors for A11Y

README.md
There was actually no link to issue tracker from readme.
=> Fix link to issue tracker

packages/uui-menu-item/lib/uui-menu-item.element.ts
=> fix: inherit font weight for uui-menu-item

packages/uui-menu-item/lib/uui-menu-item.element.ts
=> fix: add custom property for menu border radius

packages/uui-range-slider/lib/uui-range-slider.element.ts, packages/uui-range-slider/lib/uui-range-slider.story.ts
This PR adds a `readonly` state for the `uui-range-slider` component.
=> Feat: Readonly state for uui-range-slider

packages/uui-ref-node/lib/uui-ref-node.element.ts, packages/uui-ref-node/lib/uui-ref-node.story.ts, packages/uui-ref/lib/uui-ref.element.ts
This PR adds a `readonly` state for the `uui-ref` components.
=> Feat: Readonly state for uui-ref

packages/uui-card-media/lib/uui-card-media.test.ts, packages/uui-color-picker/lib/uui-color-picker.element.ts, packages/uui-color-picker/lib/uui-color-picker.test.ts, packages/uui-combobox/lib/uui-combobox.test.ts, packages/uui-file-preview/lib/uui-file-preview.test.ts, packages/uui-input-file/lib/uui-input-file.test.ts, packages/uui-symbol-file-thumbnail/lib/uui-symbol-file-thumbnail.test.ts, packages/uui-tabs/lib/uui-tabs.test.ts, web-test-runner.config.mjs
Mutes / fixes a lot of warnings in the tests.
=> test: mute warnings

packages/uui-radio/lib/uui-radio.story.ts
A minor typo in story of radiobutton component.
=> Update typo in story for radiobutton

packages/uui-boolean-input/lib/uui-boolean-input.element.ts
Fixes issue described in:
https://github.com/umbraco/Umbraco.UI/pull/874
=> Fix: make boolean inputs fit dedicated space

packages/uui-ref-node/lib/uui-ref-node.element.ts
Add name slot, to enable markdown element to be inserted into name
=> Feature: uui-ref-node, name slot

packages/uui-input/lib/uui-input.story.ts
Add story for `readonly` state of `<uui-input>`.
I also fixed bugs of some of the other stories, which didn't render anything.
=> Story for input readonly

packages/uui-color-picker/lib/uui-color-picker.element.ts
Add `ponter` cursor style to color picker button instead as most also pickers and selectable elements.
=> Add pointer cursor to color picker button

packages/uui-box/lib/uui-box.element.ts, packages/uui-button/lib/uui-button.element.ts, packages/uui-icon/lib/uui-icon.element.ts, packages/uui-ref-node/lib/uui-ref-node.element.ts
This PR center aligns the icons
=> Fix: center align icons

packages/uui-card-block-type/lib/uui-card-block-type.element.ts, packages/uui-card-media/lib/uui-card-media.element.ts, packages/uui-card/lib/uui-card.element.ts, packages/uui-combobox-list/lib/uui-combobox-list-option.element.ts, packages/uui-css/lib/custom-properties.story.ts, packages/uui-css/lib/custom-properties/sizes.css, packages/uui-css/lib/guidelines.story.ts, packages/uui-css/lib/uui-font.css, packages/uui-css/lib/uui-text.css, packages/uui-select/lib/uui-select.element.ts, packages/uui-tabs/lib/uui-tab.element.ts
Changes the base font size to 14px, to fit with Backoffice use.
=> Improvement: Set Font size 14, as we do in Backoffice

packages/uui-symbol-more/lib/uui-symbol-more.element.ts
fixes to the symbol inherits the current color.
=> More Symbol inheriting current color

packages/uui-ref-node/lib/uui-ref-node.element.ts
This PR should be corrected in the RC. so here a double PR for the same change.
=> Hotfix: Remove extra margin on ref-node (#1037)

packages/uui-input/lib/uui-input.element.ts
Gave host "color" to make sure things like text in date picker are aligned with the theme chosen, as well as giving it a color scheme option
=> Gave host "color" to make sure things like text in date picker are aligned with theme, as well as giving it a a color scheme option

packages/uui-button-copy-text/lib/uui-button-copy-text.element.ts
Just a minor typo I noticed in `uui-button-copy-text`.
=> Fix typo in comment

.github/ISSUE_TEMPLATE/config.yml
Update reference from `our.umbraco.com` to the new `forum.umbraco.com`
=> 📝 Update Issue template link to new Umbraco forum
