umbraco/Umbraco.UI

packages/uui-avatar/README.md

I'd noticed that the example of the [`<uui-avatar>` component](https://github.com/umbraco/Umbraco.UI/tree/dev/packages/uui-avatar) uses `src` instead of `img-src`.
Following an example of how to use the [`<uui-avatar>` component](https://github.com/umbraco/Umbraco.UI/tree/dev/packages/uui-avatar), I noticed that the README's example uses the `src` attribute, but that didn't work, and saw on Storybook that the attribute is `img-src` instead.

Corrected attribute on `uui-avatar` example

---

packages/uui-button/lib/uui-button.element.ts

This PR adds a `--uui-button-font-size` custom property that allows changing font size for many buttons in nested shadow dom trees

add --uui-button-font-size custom property

---

packages/uui-button/lib/uui-button.element.ts
packages/uui-icon-registry-essential/lib/uui-icon-registry-essential.test.ts
packages/uui-icon-registry/lib/uui-icon-registry.element.ts
packages/uui-icon/lib/uui-icon.element.ts

Make another attempt to retrieve the icon on firstUpdated. This is relevant in light-DOM where elements are constructed from the bottom-up.
Additionally, I made sure to use uui-icon for uui-button.

Fix uui-icon for light-DOM context

---

packages/uui-avatar/lib/uui-avatar.element.ts

I noticed in the advanced table example using `<uui-avatar>` that this was squeezed on smaller screen sizes.
**Before**
**After**

Don't squeeze avatar

---

packages/uui-avatar/lib/uui-avatar.element.ts

Adds an `aspect-ratio: 1` property to `uui-avatar`.
Fixes #139
Prevents squeezing the avatar circle when the parent container is narrow. 
`aspect-ratio` is now accepted in all latest versions of modern browsers 🥳

add aspect-ratio property to avatar host element

---

packages/uui-avatar-group/lib/uui-avatar-group.element.ts
packages/uui-breadcrumbs/lib/uui-breadcrumbs.element.ts
packages/uui-breadcrumbs/lib/uui-breadcrumbs.test.ts
packages/uui-table/lib/uui-table-row.element.ts
packages/uui-table/lib/uui-table-row.test.ts
packages/uui-tabs/lib/uui-tab-group.element.ts
packages/uui-tabs/lib/uui-tabs.story.ts
packages/uui-tabs/lib/uui-tabs.test.ts

This adds support for having unknown slotted elements in places like uui-breadcrumb and uui-tab-group by checking up on other query selectors such as role=tab or role=listitem and optionally classes that make sense.
This also replaces `@queryAssignedNodes` with `@queryAssignedElements` because the former is marked as deprecated with the options we provided it such as "flatten". QueryAssignedElements works exactly the same, only it takes in an options object (though I believe the new version of queryAssignedNodes does the same) so Lit can add new options in the future without messing with the API. It also has the advantage of returning HTMLElement's instead which are a bit more useful.
Fixes [AB#17169](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17169) …

Add support for unknown elements

---

packages/uui-toggle/lib/uui-toggle.element.ts

UUI-Toggle: change adjacent sibling combinator to general sibling
This PR changes the way of styling the toggle `#slider` element when it is determined by the state of `input` element. 
The adjacent sibling CSS combinator (+) is changed to (~) in every selector.  closes #152
This allows a more flexible extending the `UUIToggleElement` class. It allows adding additional elements to the markup without breaking the slider's style.

fix: uui-toggle change adjacent sibling combinator to general sibling

---

packages/uui-boolean-input/lib/uui-boolean-input.element.ts

Hidden native input behind custom UI, just moved up a little, as it was peaking out on Safari.

Hide native input in Safari.

---

packages/uui-base/lib/registration/index.ts

This PR removes the warning if a custom element is registered under the same name as an already registered custom element.

Remove define element warning

---

package-lock.json
packages/uui-avatar-group/package.json
packages/uui-avatar-group/tsconfig.json
packages/uui-button-group/package.json
packages/uui-button-group/tsconfig.json
packages/uui-button/lib/uui-button.element.ts
packages/uui-button/package.json
packages/uui-button/tsconfig.json
packages/uui-card-content-node/lib/uui-card-content-node.element.ts
packages/uui-card-media/lib/uui-card-media.element.ts
packages/uui-card-user/lib/uui-card-user.element.ts
packages/uui-checkbox/package.json
packages/uui-checkbox/tsconfig.json
packages/uui-form-layout-item/lib/uui-form-layout-item.element.ts
packages/uui-form-layout-item/package.json
packages/uui-form-layout-item/tsconfig.json
packages/uui-input-lock/lib/uui-input-lock.element.ts
packages/uui-input-lock/package.json
packages/uui-input-lock/tsconfig.json
packages/uui-input-password/lib/uui-input-password.element.ts
packages/uui-menu-item/lib/uui-menu-item.element.ts
packages/uui-menu-item/package.json
packages/uui-menu-item/tsconfig.json
packages/uui-pagination/lib/uui-pagination.element.ts
packages/uui-ref-node/lib/uui-ref-node.element.ts
packages/uui-toast-notification-layout/package.json
packages/uui-toast-notification-layout/tsconfig.json
packages/uui-toast-notification/lib/uui-toast-notification.element.ts
packages/uui-toast-notification/package.json
packages/uui-toast-notification/tsconfig.json

This PR implements `demandCustomElement` for all elements that require other uui-elements. We want to make sure a uui component renders correctly in even given state. demandCustomElement adds a console warn if a required uui-element is not registered in the browser.

Implement demandCustomElement for all packages

---

.github/workflows/chromatic.yml

This greatly reduces the amount of snapshots used. We have already exhausted our 5000 snaps for this month after only 4 days.

Add --only-changed to Chromatic

---

packages/uui-keyboard-shortcut/lib/uui-key.element.ts
packages/uui-keyboard-shortcut/lib/uui-keyboard-shortcut.test.ts

This PR adds the missing defineElement decorator to uui-key. When the element got correctly defined the test broke in safari because of the `&#8593;` in the test. 
I have changed the lowercase logic to be based on css instead of the custom changeCase method. I can't figure out if there is a scenario we need to cover that can't be handled with css?

Bugfix: Add missing uui-key element definition

---

lerna.json

Ensuring that Lerna does not bump version of a package if one of following files are changed.

added ignoreChanges

---

packages/uui/package.json

Looks like the uui package is missing a single reference to another package making it not work when imported as es module.

fix: add missing reference to uui-input-lock for uui

---

packages/uui-box/lib/uui-box.element.ts
packages/uui-box/lib/uui-box.test.ts

Do not set the CSS custom property --uui-box-default-padding locally, as that prevents it begin set on a global level.
I as well added tests to prove that it is inherited from a parent.

UUI-Box: Removing local definition of --uui-box-default-padding

---

packages/uui-input/lib/uui-input.element.ts

This PR changes the modifier on `_onIput` method from `private` to `protected`. This allows overriding this method by a class that extends `UUIInputElement` and implementing some extra logic happening when the user inputs a value.

change _onInput method from private to protected

---

packages/uui-button/lib/uui-button.element.ts

This changes the button display value so that it no longer extends to 100% of the container.
Changes display form inline-block to inline-flex on UUI Button.
No one likes 100% height buttons..

Fixed button height.

---

packages/uui-select/lib/uui-select.element.ts
packages/uui-select/lib/uui-select.test.ts

This PR fixes bug in UUISelect caused the element to have an empty value despite of an option being set to selected. 
In the `willUpdate` if property `options` is changed the value of uui-slect element will be set to the value of the selected option if it is present. On top of that the value of native select in the shadow dom is now bind to the `value` property of the `UUISelect` and it is not possible to set the value to something different then values of the options. This behavior fully reflects the native select. 
When the elememnt has preselected option the value should reflect the value of the option. It should not be possible to set the value to something different then values of the options.

UUI-Select: set the element value to the value of selected option

---

packages/uui-toast-notification/lib/uui-toast-notification.element.ts

uui-toast-notification did not parse the color prop correctly, so it did still have the primary look with default color.
example of error:
this fix changes it to:

fix the color of the toast notification close button

---

packages/uui-symbol-expand/lib/uui-symbol-expand.element.ts
packages/uui-symbol-sort/lib/uui-symbol-sort.element.ts

Adding CSS height and width to expand the symbol.
Adding xmlns to SVGs
fixes https://github.com/umbraco/Umbraco.UI/issues/225

Fix expand SVGs in safari

---

packages/uui-button/lib/uui-button.element.ts
packages/uui-combobox/lib/uui-combobox.element.ts
packages/uui-input-lock/lib/uui-input-lock.element.ts
packages/uui-input-password/lib/uui-input-password.element.ts
packages/uui-input/lib/uui-input.element.ts
stories/scaffolding/app-header/app-header.example.ts

By removing top and bottom padding, content always stays vertically aligned.
This make it simpler to implement, and there by only require implementors to set --uui-button-height, to squeeze the button height.
Fixes https://github.com/umbraco/Umbraco.UI/issues/227
Co-authored-by: Niels Lyngsø <niels.lyngso@gmail.com>

Allow uui-button to fit in less tall contexts

---

packages/uui-css/lib/uui-text.css
packages/uui-table/lib/uui-table-cell.element.ts
packages/uui-table/lib/uui-table-row.element.ts

Fixing table-cell disable-child-interaction as after element went over the edge of the cell.
also fixing so outlines only show when using keyboard interaction
and correction colors of uui-text as they were forgotten when implementing the new color system.

fix: disable-child-interaction going over edges + other details

---

packages/uui-button/lib/uui-button.element.ts
packages/uui-button/lib/uui-button.story.ts

Use flex-box (flex-inline) to vertical align content of UUI-Button anchor tag

fix: vertical align content of UUI-Button anchor tag

---

packages/uui-toast-notification/lib/uui-toast-notification.element.ts

`uui-notification` css does not follow look/color system. This PR fixes that.
Notification element was acceping primary to the color property.

fix: change notification color primary to default

---

packages/uui-toast-notification/lib/uui-toast-notification.element.ts

This PR fixes mistake in `uui-notification` jsdocs color block

Update uui-toast-notification docs

---

packages/uui-button/lib/uui-button.element.ts
packages/uui-input-file/lib/uui-input-file.element.ts

This PR changes `height` to `min-height` in the uui-button component
Because the height is fixed on the button, it cannot handle more then 1 line. See picture. 
By changing the `height` to `min-height` the button can stretch nicely.

Change `uui-button` height to min-height and remove the height from `button` inside

---

packages/uui-combobox/lib/uui-combobox.element.ts
packages/uui-form-validation-message/lib/uui-form-validation-message.element.ts

fixes https://github.com/umbraco/Umbraco.UI/issues/263
The uui-form-validation-message was using event target to identify the component. It turned out that because we now have bubbling events, the events from the search input also got registered as the combobox and since it's always valid that overwrote the state of the combobox. This is fixed by using `.composedPath()[0]`
We also had some internal state of combobox that wasn't handled right, so cleaned up the values a bit.
Fixes the following cases:
- Clear button doesn't clear search result
- Typing in search field and closing the dropdown hides the value
- Validation message of combobox does not always show up in uui-form-validation-message
See issue.

Fix various issues of combobox and related

---

packages/uui-ref-node-data-type/lib/uui-ref-node-data-type.story.ts
packages/uui-ref-node-document-type/lib/uui-ref-node-document-type.story.ts
packages/uui-ref-node-form/lib/uui-ref-node-form.story.ts
packages/uui-ref-node-member/lib/uui-ref-node-member.story.ts
packages/uui-ref-node-package/lib/uui-ref-node-package.story.ts
packages/uui-ref-node-user/lib/uui-ref-node-user.story.ts
packages/uui-ref-node/lib/uui-ref-node.story.ts

Fixes issue: #297
Adds missing `essential-icon-registry` wrapper for ref nodes stories.
Also renames some custom icons

FIXES:#297 - Missing custom icon for reference nodes in Storybook

---

packages/uui-combobox/lib/uui-combobox.element.ts
packages/uui-scroll-container/lib/uui-scroll-container.element.ts

Fixes a bug that would close the combobox when clicking an option but not select it.
Fixes focus issues on the combobox. Now you can only focus the input and the clear button (only when visible).

fix focus issues on uui-combobox

---

packages/uui-button/lib/uui-button.story.ts

This is just typo fix in the label on an example in the Button Looks and Colors story.

Fix typo in Button Looks and Colors Story

---

packages/uui-input-lock/lib/uui-input-lock.element.ts

I noticed that Input lock violated an accessibility check regarding color contrast. So I bumped the opacity of the input a bit, to make it pass.
```
Element has insufficient color contrast of 3.89 (foreground color: #7a7a7b, background color: #f3f3f5, font size: 11.3pt (15px), font weight: normal). Expected contrast ratio of 4.5:1
```

[Input lock] Bump opacity a bit, to pass color contrast accessibility check

---

README.md

The installation instruction was missing the choose directory command after cloning the git repo.
I added one line of command code.

fix: Add cd to installation instruction before npm install

---

packages/uui-combobox/lib/uui-combobox.story.ts

When searching in the combo box for both avatar and simple ignore case.
Resolution to [Issue 357](https://github.com/umbraco/Umbraco.UI/issues/357)
Load Storybook, open Combobox Avatar and search for **r2**. You will then see R2-D2 in the results.

Case insensitivity when using combobox-avatar

---

packages/uui-pagination/lib/uui-pagination.element.ts

When updating the total number of pages within the Pagination component the render wasn't being rerendered.
This fix is to resolve [Issue 355](https://github.com/umbraco/Umbraco.UI/issues/355)
Run storybook, go to the pagination overview and change the number of pages. The number of pages shown in the component will automatically update.

Have pagination render update 

---

packages/uui-input/lib/uui-input.element.ts

This PR changes `uui-input` host element `align-items` css property from `center` to `stretch`.
It fixes the problem of white frame apearing around the autocompleted input. 
You can fix this also by giving the embeded input a `height: 100%` .
To my best knowledge this is not a breakig change but the above approach might be safer. 
Fixes #361

uui-input change aling-items to stretch

---

packages/uui-card-media/lib/uui-card-media.element.ts

Rendering bug caused by invalid property accessor, which was missed due to `any` typing. We were attempting to access `e.path` where `e` was `any` (but was actually a generic `Event`), if we had typed correctly we'd have caught the issue, and not attempted to access `path` and used the correct `compiledPath()`.
Fixes #401 
Build, verify media card renders correctly (and no more console error):
Before:
After:

uui-card-media does not render images correctly

---

packages/uui-input-file/lib/uui-input-file.element.ts

Change updates uui-input-file to only show the add button only when multiple is true, or when no files are selected (single-file mode).
The picker works correctly in it's current shape (ie single mode only allows one file, multiple allows many), I'm just not sure the UI makes sense - continuing to display the Add button after selecting a file in single mode is potentially confusing, even though the button will replace the existing selection. 
Alternatively could consider changing the button text when a file is selected in single-mode (ie `Replace` or `Change selection` or something similar)
I won't lose a minute of sleep if the current implementation is preferred.

uui-input-file => Only show add button when multiple or no file selected

---

packages/uui-icon/lib/uui-icon.element.ts
packages/uui-input/lib/uui-input.story.ts

When rendering an icon in the prepend or append slot in the uui-input component, the icon was lacking whitespace:
Changes here add whitespace (Append example has inline background color and left-padding):
For simplicity, the icon has a left-margin when prepended, and a right margin when appended, to move it off the input edge in both cases. Additional styling would need to depend on the context (ie an appended icon with a background color would need additional padding on the left side to separate the input text), which would need to be managed in the specific implementation.
Vertical alignment relies on the icon not being slotted directly, but using an enclosing element (this is the existing behaviour before this change):
```
<div
slot="append"
style="background:#f3f3f3; …
```

fix: Add whitespace when appending/prepending icon in uui-input

---

packages/uui-radio/lib/uui-radio-group.element.ts
packages/uui-radio/lib/uui-radio-group.test.ts
packages/uui-radio/lib/uui-radio.story.ts

Fixed an issue where having a start/initial value on the radio-group would throw errors and not propagate to it's child radio buttons.
Added test for start value on radio-group

bugfix: radio-group initial value not working

---

packages/uui-combobox/lib/uui-combobox.element.ts
packages/uui-combobox/lib/uui-combobox.story.ts
packages/uui-combobox/lib/uui-combobox.test.ts
packages/uui/tsconfig.json

This PR adds a `disabled` property to `uui-combobox` element. The value it passed down to the `uui-input` rendered by the component, therefore fixes #412 . 
It does not add readonly property becasue native `select` element does not have one. 
Although PR fixex a big it actually introduces new feature, the ability to disable the element, it it therefore tagged as new feature, not as a bug fix.

add disabled property to uui-combobox

---

packages/uui-scroll-container/lib/uui-scroll-container.element.ts
packages/uui-scroll-container/lib/uui-scroll-container.story.ts
packages/uui-scroll-container/lib/uui-scroll-container.test.ts

uui-scroll-container is now auto on overflow - the scrollbar will only appear if needed.
- Added option to use enforce-scroll on the element to make the scroll always appear.
- Updated test file
- Added an extra story about enforce scroll.

scroll container is now auto scroll and has an enforce scroll option

---

packages/uui-ref-list/lib/uui-ref-list.element.ts

make the border between items(before element) fit within the width of the list.

Fix so uui-ref-list border fits within the given space.

---

packages/uui-base/lib/mixins/LabelMixin.ts
packages/uui-button/lib/uui-button.element.ts

* Add documentation for the slots of uui-button.
* Remove the inherited 'default' slot documentation from LabelMixin, since each component that uses LabelMixin knows best how to describe what it's doing with label slot, which most of them renames anyway, and some may not even call the `renderLabel` method.

uui-button slot documentation

---

packages/uui-file-dropzone/lib/index.ts

It is not possible to import the event called `UUIFileDropzoneEvent` from anywhere.

fix: uui-file-dropzone does not export its event classes

---

packages/uui-file-dropzone/lib/uui-file-dropzone.element.ts
packages/uui-file-dropzone/lib/uui-file-dropzone.story.ts

The event UUIFileDropzoneEvent stipulates that the "detail" object is of type `File[]`. However, when debugging at runtime you could see that the files were of type `FileEntry`, which is an older API. This was due to the fact that the partly supported Webkit method `webkitGetAsEntry()` was being used for dropped files (DataTransferItem's).
The remediation is to use the `getAsFile()` method instead and also to make sure, that `webkitGetAsEntry()` which is still useful for directories is being hidden away behind a guard statement.
In order to actually use the `File` interface instead, we also have to avoid pushing directory entries themselves to the event detail object but instead, only scan them and let their own entries enter the queue to be parsed (if supported in the browser).
Lastly, …

fix: uui-file-dropzone does not follow the inferred interface for dropped files

---

packages/uui-base/lib/mixins/SelectableMixin.ts
packages/uui-table/lib/uui-table-cell.story.ts
packages/uui-table/lib/uui-table-row.story.ts

Fixes #437
If an input field is placed inside a table cell, you cannot type spaces in the field due to the fact that the surrounding uui-table-row is listening on "keydown" events and preventing them from bubbling.
This PR aims to make all events in the SelectableMixin act the same way so that we do not interfer with native events.
However, one caveat is that placing a uui-input inside a uui-table-row that is selectable will **select** that row when you click inside the field. There does not seem to be a way to prevent this, since we can only check on the `composedPath()` to detect which element you clicked on due to the generics of how the SelectableMixin works. Nothing bad happens when you do this, but you need to be aware of this caveat.
1. There is a story set up to test this scenario …

fix: keydown events are prevented from bubbling in uui-table-cell

---

packages/uui-color-area/lib/uui-color-area.element.ts

Fixed bug when dragging handle in color area, where handle jumped to left position reported in https://github.com/umbraco/Umbraco.UI/issues/463
https://github.com/umbraco/Umbraco.UI/assets/2919859/7f2f925a-bf25-405a-8d46-0db142877639
With changes in this PR:
https://github.com/umbraco/Umbraco.UI/assets/2919859/4ffc61e0-af84-4542-95a1-9c10b178e8c8

Fix dragging in color area and sync value

---

packages/uui-file-dropzone/lib/uui-file-dropzone.element.ts

Fixes #485
It is not possible to drag & drop files containing multiple dots in their name when using an "accept" filter.
This PR aims to change the behavior so that first and foremost, we split file names by `.` and then use the **last** dot and not the first.
Secondly, we are now treating and dividing accept parameters in a *setter* on the property so that it is only done once, and we now also support receiving file extensions both with and without a `.` in the accept property.
1. Open Storybook and go to the "Accept" story
2. Change the 'accept' property to something like "png" and try and upload files with one and two commas.

fix: not possible to drag&drop file with multiple dots

---

packages/uui-color-area/lib/uui-color-area.element.ts
packages/uui-color-slider/lib/uui-color-slider.element.ts

When `<uui-color-area>` has `disabled` attribute it has some opacity and `not-allowed` cursor.
The `<uui-color-slider>` did not, so it wasn't clear the slider was disabled besides it wasn't possible to drag handle.
This PR makes this more consistent.

Make color slider disabled state consistent with disabled color area

---

packages/uui-color-swatches/lib/uui-color-swatches.story.ts

… with example where label is different than value.
Update the story of color swatches to use array of objects instead to show label can be different than value.
while string array still works.

Update story for color swatches

---

packages/uui-color-area/lib/uui-color-area.story.ts
packages/uui-color-picker/lib/uui-color-picker.story.ts
packages/uui-color-slider/lib/uui-color-slider.story.ts
packages/uui-color-swatch/lib/uui-color-swatch.element.ts
packages/uui-color-swatch/lib/uui-color-swatch.story.ts
packages/uui-color-swatches/lib/uui-color-swatches.element.ts
packages/uui-color-swatches/lib/uui-color-swatches.story.ts

Fixes #499 
Not all properties are mapped through Storybook for the uui-color-* components. This aims to rectify that by changing to the new StoryObj (CSF3) format, which automaps properties.
This PR also fixes a small error with web-component-analyzer output for the `@type` jsdoc parameter.

docs: storybook color props

---

packages/uui-modal/lib/uui-modal.element.ts

Adds z-index to the modal backdrop to prevent elements from overlaying.
Examples:
Currently:
Fix:

Modal backdrop z-index

---

packages/uui-base/lib/mixins/SelectableMixin.ts
packages/uui-menu-item/lib/uui-menu-item.element.ts
packages/uui-menu-item/lib/uui-menu-item.story.ts
packages/uui-menu-item/lib/uui-menu-item.test.ts

This PR adds a select-mode property for the uui-menu-item to differentiate between persisting selection and highlight selection.
The default is undefined (persisting), where highlight changes style of menu-item when selected and selectable.
Also a small fix where it didn't show the caret symbol in storybook 😄 
Highlight
Persisting

select mode for highlight

---

packages/uui-loader-bar/lib/uui-loader-bar.story.ts

Just noticed that the uui-loader-bar showed the uui-loader in the code examples, so I fixed the typo in the story.
https://uui.umbraco.com/?path=/docs/loaders-loader-bar--docs
I was trying to use the `<uui-loader-bar>` and noticed the code example in the story was the same as `<uui-loader>`
Check the story here:
https://uui.umbraco.com/?path=/docs/loaders-loader-bar--docs

Typo in story for uui-loader-bar

---

packages/uui-tabs/lib/uui-tabs.story.ts

I've improved the `uui-tabs` Storybook documentation.
See issue #356 
I saw [Julia's issue](https://github.com/umbraco/Umbraco.UI/issues/356) and decided that it was a quick fix. I did actually also stumble upon the issue myself, when searching Storybook for documentation regarding `uui-tabs`.
This fix makes it easier to copy the correct code.
Run the `npm run storybook` command and navigate to the **Tabs** section.
`Direct relative path is _/?path=/docs/buttons-tabs--docs#with-icons_

docs(storybook): add icon slot example for uui-tab element (#356)

---

.gitignore
.vscode/settings.json
packages/uui-base/lib/types/InterfaceHeading.ts
packages/uui-base/lib/types/index.ts
packages/uui-box/README.md
packages/uui-box/lib/uui-box.element.ts
packages/uui-box/lib/uui-box.story.ts
packages/uui-box/lib/uui-box.test.ts
typings.d.ts

fixes #447 
Story at /docs/layout-box--docs been updated to include new property headerVariant
Change dropdown to a different H tag and inspect element to see component now renders with the H tag selected rather than then always h5

uui-box: add a property to control the headline variant

---

packages/uui-button/lib/uui-button.element.ts
packages/uui-button/lib/uui-button.story.ts

Adds a css variable to adjust alignment of content in the button. `--uui-button-content-align` which accepts the following values: `left` `right` `center`
Some buttons needs to have left aligned content. An example is the external login providers on the login screen.

uui-button: content align css variable

---

packages/uui-input/lib/uui-input.element.ts

In the scenario of uui-input being set to 100% and having an append attached to it, there is a visual bug where the appended element doesn't go to the end. The new auto-width feature causes this bug.
Before fix (current)
After fix (pull request)

fixed an issue caused by autowidth

---

packages/uui-card-content-node/lib/uui-card-content-node.element.ts
packages/uui-card-content-node/lib/uui-card-content-node.story.ts
packages/uui-card-media/lib/uui-card-media.element.ts
packages/uui-card-media/lib/uui-card-media.story.ts
packages/uui-card-user/lib/uui-card-user.element.ts
packages/uui-card-user/lib/uui-card-user.story.ts
packages/uui-card/lib/uui-card.element.ts

This adds  href property to all cards, which should be used instead of the button click event. However this is non-breaking so already implemented still works.

Add href to cards

---

packages/uui-tabs/lib/uui-tab.element.ts

Changing the horizontal padding of uui-tabs' `#button` to `--uui-size-5` (Task 32426)

horizontal padding

---

templates/plop-templates/component.ts.hbs

I noticed when generating a new package the component has a whitespace, but later the linter warns about the formatting here.

Remove whitespace before semicolon when generating new package

---

.devcontainer/devcontainer.json
.vscode/settings.json
.vscode/tasks.json

This adds support for GitHub Codespaces to ensure easier contributions to the project without having to worry about dependencies
This helps first time contributors and others to get straight into coding and not have to worry about dependencies, this also preconfigures VSCode with preferred extensions and settings to help with a nice DX
* Create a CodeSpace
* Inside VSCode open a terminal and switch to the branch for this PR
* Use VSCode command palette `CTRL + SHIFT + P` and search for `Codespaces: Full Rebuild Container`
* `npm install` should have already run and the `node_modules` folder should be present already
* The Code Spellchecker extension and the Prettier VSCode extension are installed
* The port for Storybook is defined

Add support for GitHub Codespaces

---

packages/uui-icon/lib/uui-icon.element.ts

Add option to set alternative label of icon. If no label has been set, it will set `aria-hidden` attribute.
Discussed in https://github.com/umbraco/Umbraco-CMS/pull/14780#discussion_r1341254646

Set aria-hidden if no label has been set

---

package-lock.json
packages/uui-tabs/lib/uui-tabs.story.ts
packages/uui-tabs/tsconfig.json

Fixing missing package references for UUI-tab towards some of the components is uses.
As well to add a story for HREF, as I like to highlight this feature so we can ensure the quality of this feature going forward.

fixing imports for UUI-Tab + story for href property

---

packages/uui-color-picker/lib/uui-color-picker.element.ts

Add HSV as accepted color format

---

packages/uui-radio/lib/uui-radio.story.ts

While going through the storybook I noticed a missing bracket in one of the radio button code examples.
The missing bracket was causing the example code to not be correctly highlighted and if you used the "copy" functionality you would be copying malformed html.
https://uui.umbraco.com/?path=/docs/uui-radio--docs#radio-group

Added missing bracket to uui-radio story

---

.github/pull_request_template.md

While making another pull request I noticed that one of the checklist items of the PR template was pointing to a non existing contributing link 😅
I replaced it with the one in branch `v1/contrib`, I hope that is the correct one!

Updated contributing link in pull request template

---

packages/uui-textarea/lib/uui-textarea.element.ts

Fixes the issue where the height of textarea would render incorrectly on initial load, if textarea is set to "auto-height" and the initial value is multiple lines long.
The bug was caused by something related to the font family inherited. Fixed the issue by setting an initial line height of textarea.

text area autoheight fix

---

packages/uui-file-dropzone/lib/uui-file-dropzone.element.ts

Small bugfix where the accept string didnt get added to the actual element

fix: uui-dropzone should set the 'accept' attribute

---

packages/uui-popover-container/lib/uui-popover-container.element.ts
packages/uui-popover-container/lib/uui-popover-container.mdx

This PR makes sure that the popover container always has the `popover` attribute as it is needed by the native Popover API.
It checks if a popover value is already present (example `popover='manual'`) to prevent unwanted overides.
Also updates the docs to reflect the changes
Now you can use the popover as such:
```html
<uui-popover-container id="my-popover">
...content
</uui-popover-container>
```
instead of 
```html
<uui-popover-container id="my-popover" popover>
...content
</uui-popover-container>
```

uui-popover-container: set popover attribute automatically

---

packages/uui-menu-item/lib/uui-menu-item.element.ts
packages/uui-menu-item/lib/uui-menu-item.story.ts

Adds a css var: `--uui-menu-item-flat-structure` to menu item to remove the indentation of the chevron for when you know you won't have nesting (a flat structure)

uui-menu-item: add flatten css var to hide chevron column

---

packages/uui-button/lib/uui-button.element.ts
packages/uui-checkbox/lib/uui-checkbox.element.ts
packages/uui-color-swatch/lib/uui-color-swatch.element.ts
packages/uui-toggle/lib/uui-toggle.element.ts

Correct icons and implementation.
Get the right look of icon and get the right colors.
And fix the look as this did un intentional change when all the icons where switched out ofr Lucide icons.

Adjust components to new icon set

---

.eslintrc.js
packages/uui-combobox/lib/uui-combobox-async-example.ts
packages/uui-combobox/lib/uui-combobox-async-options-example.ts
packages/uui-modal/lib/modal-example.element.ts
packages/uui-modal/lib/uui-modal-container.ts
packages/uui-modal/lib/uui-modal-dialog.element.ts
packages/uui-modal/lib/uui-modal-sidebar.element.ts
packages/uui-table/lib/uui-table-advanced-example.ts

The custom `defineElement` decorator is now used instead of the default lit `customElement`.
Also adds an ESLint rule configured as a warning, to try to prevent this in the future.
The custom `defineElement` decorator prevents elements from being registered multiple times.
This is partially related to https://github.com/umbraco/Umbraco-CMS/issues/15397.

Ensure defineElement is used instead of customElement

---

packages/uui-combobox-list/lib/uui-combobox-list-option.element.ts

Fixing padding according to this issue: https://github.com/umbraco/Umbraco.UI/issues/666
Before and after:

fix: padding fixes for uui-combobox

---

packages/uui-combobox-list/lib/uui-combobox-list.element.ts
packages/uui-combobox/lib/uui-combobox.element.ts
packages/uui-combobox/lib/uui-combobox.story.ts
packages/uui-combobox/package.json

This PR Fixes issues with how the combobox handles the active item. Meaning the one that gets highlighted when you navigate with the arrow keys or click an item.
Before the active item was unreliable and not correctly shown visually.
This PR also correctly sets the first item as active when you open the combobox, or make changes to the children, eg. when you search. Example: If you search for "ora" and the first item is orange, pressing space will now pick orange.
Before you would have to click the item, or navigate to it using the arrow keys before pressing enter.
Also adds the expand symbol instead of the custom svg implementation.

fix: uui-combobox should correctly handle the active item

---

packages/uui-card-media/lib/uui-card-media.element.ts
packages/uui-combobox/lib/uui-combobox.element.ts
packages/uui-tabs/lib/uui-tab-group.element.ts

Elements should not import other elements directly but instead utilize the `demandCustomElement` function. This fixes a few components that were doing this as well as organizing the imports.

fix: direct imports are not allowed

---

packages/uui-box/lib/uui-box.element.ts

Ability to set padding on the header.
So the content can go to the edge

append new css custom property to overwrite header padding

---

packages/uui-ref-node-data-type/lib/uui-ref-node-data-type.story.ts
packages/uui-ref-node-document-type/lib/uui-ref-node-document-type.story.ts
packages/uui-ref-node-form/lib/uui-ref-node-form.story.ts
packages/uui-ref-node-member/lib/uui-ref-node-member.story.ts
packages/uui-ref-node-package/lib/uui-ref-node-package.story.ts
packages/uui-ref-node-user/lib/uui-ref-node-user.story.ts
packages/uui-ref-node/lib/uui-ref-node.story.ts
packages/uui-ref/lib/uui-ref.element.ts

Changes the border attribute on ref to standalone to align with our naming
Also adds missing JSDocs for ref

Ref Element: Change border attribute to standalone

---

packages/uui-ref/lib/uui-ref.element.ts

Changes the the button on ref to use `uui-color-text` css var instead of the default `buttontext` value

Ref: Use css var for text

---

packages/uui-ref-node/lib/uui-ref-node.element.ts
packages/uui-ref-node/lib/uui-ref-node.story.ts

Adds href and target to ref-node
Also fixes import issues in ref node

feat: uui-ref-node should have href and target properties

---

packages/uui-button/lib/uui-button.story.ts
packages/uui-tabs/lib/uui-tab-group.element.ts
packages/uui-tabs/lib/uui-tab.element.ts
packages/uui-tabs/lib/uui-tabs.story.ts

Adds CSS variable to add gaps between tab items.
`--uui-tab-group-gap`
Only pixel values are valid. Any other value will be converted to pixels if possible. Invalid number values will fallback to 0
Examples `20em => 20px` `25% => 25px` `10 => 10px` `100whatever => 100px` `sdh10 => NaN => 0px`

uui-tab-group does not support having a gap between tabs

---

packages/uui-button-inline-create/lib/uui-button-inline-create.element.ts
packages/uui-button-inline-create/lib/uui-button-inline-create.story.ts

Adds href and target properties to inline button create
Also fixes the placement of the button so it is no longer offset to the side.

Inline-button-create: Add href

---

packages/uui-tabs/lib/uui-tab-group.element.ts

The element, like any custom element defaults to inline. Tab group should be a block element.

set display to block on uui-tab-group 

---

packages/uui-icon-registry-essential/lib/svgs/iconAdd.ts

The `add` icon in icon registy essential was dispolayed as a plug, not plus.  This PR corrects that.

Fix incorrect add icon

---

packages/uui-tabs/lib/uui-tab-group.element.ts
packages/uui-tabs/lib/uui-tabs.story.ts

Fixes memory leaks and layout issues in tab group.
Added support for async tabs, including async layout changes inside a tab.
Added stories to demonstrate flex layouts.

fix(uui-tab-group): async tabs are not calculated correctly and have memory leaks

---

packages/uui-tabs/lib/uui-tab-group.element.ts
packages/uui-tabs/lib/uui-tabs.story.ts
packages/uui-tabs/lib/uui-tabs.test.ts

Fixes layout issues caused by changes made in 1.6
Changed the tab group to use display flex instead of contents as a common use case is to add borders on some or all sides of the tab group. With display contents the tab group would have had to be wrapped in another element with a border on, or we would have to add 5 css vars, one for each side and one for all sides.

fix(uui-tab-group): layout is causing issues due to missing `display: flex`

---

packages/uui-css/lib/custom-properties/fonts.css

Do not import the lato font here as it means you cannot import only the custom properties without getting the font.
Lato is already defined in uui-font.css and you can get all of it by uui-css.css as well.

fix(uui-css): Lato is loaded twice

---

packages/uui-textarea/lib/uui-textarea.element.ts

Same as fixed for `<uui-input>` in https://github.com/umbraco/Umbraco.UI/pull/624 but for `<uui-textarea>` as I noticed this in Umbraco 14 beta at description of properties on content type editor.

Don't hide placeholder text on focus

---

packages/uui-menu-item/lib/uui-menu-item.element.ts

Allow to change colors of different styles in menu item. closes #769
This Pr adds various custom properties for uui-menu-item, allowing a chenge of color and backgrounf colot for different states.

feat: :lipstick: add custom properties for menu item

---

packages/uui-box/lib/uui-box.element.ts

This PR adds the following custom properties to uui-box:
-  `--uui-box-border-width`, 
-  `--uui-box-box-shadow`, 
-  `--uui-box-border-radius`
closes #768
With that it is possible to implement changes required for redesign of cloud portal wich is removing the shadow, adding a border and changing the border radius of UUI-box globally

feat: :lipstick: add more custom properties to uui-box

---

packages/uui-box/lib/uui-box.element.ts

In the cloud portal we would like the ability to change the border color of uui-box to fit our theme better. Here in this PR we simply added a custom property to support that.
Currently the uui-box border color is static, we would like to be able to adapt the color to our needs. This introduces the possibility of making that possible.
overwrite the --uui-box-border-color, and see it take effect.

fix: Update uui-box.element.ts to support border color changeability

---

packages/uui-modal/lib/uui-modal.element.ts

The background of the dialog would occasionally appear in the corners of a rounded edge. This update removes the redundant background on the native dialog, as the uui-dialog already includes a background.
Before:
After:
It hurts my eyes

fix(uui-dialog): Remove native dialog background

---

packages/uui-button/lib/uui-button.element.ts

This Pr fixes what I broke before by adding keyframes back in 😅

fix: :ambulance: add back missing animation

---

packages/uui-tag/lib/uui-tag.element.ts

Extending uui-tag with custom properties in order to style it for the new modern umbraco cloud portal design.
I've added three properties to modify the padding, border-radius and border color of the uui.tag
We want the ability to adapt the uui-tag better to our own needs and styling.
Change properties

Add custom properties to uui-tag

---

packages/uui-menu-item/lib/uui-menu-item.element.ts

feat(uui-menu-item): focus method for menu-item

---

package-lock.json
package.json
packages/uui-base/lib/events/UUIFormControlEvent.ts
packages/uui-base/lib/mixins/FormControlMixin.ts
packages/uui-form-validation-message/lib/uui-form-validation-message.element.ts
packages/uui-input-file/lib/uui-input-file.element.ts
packages/uui-radio/lib/uui-radio-group.element.ts
packages/uui-range-slider/lib/uui-range-slider.element.ts
packages/uui-slider/lib/uui-slider.element.ts
packages/uui-textarea/lib/uui-textarea.element.ts

Aligning the FormControl with latest discoveries from Backoffice.
This make the form control able to be implemented like before the recent PR of https://github.com/umbraco/Umbraco.UI/pull/745
and thereby more simple. But it is still possible to overwrite the default value, and use other types for the value, but it requires setting the generics properly. But this detail should not be relevant to most.
Generally aligning with the Backoffice approach, but still setting form internals value (Backoffice one does not do that)

feat: Align FormControl implementation with latest from Backoffice Validation

---

packages/uui-boolean-input/lib/uui-boolean-input.element.ts

In boolean elements, the native input field was never truly hidden in firefox despite height/width set to 0, causing it to appear to look like dots on the screen.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16515

fix: Hide the native input for boolean elements in firefox

---

packages/uui-color-swatch/lib/uui-color-swatch.story.ts

Browsing the docs, I noticed the code samples had mismatching open- and closetags, which was probably a copy & paste error. I don't really know which boxes to tick below; neither have I done any of the required build steps, so leaving this as a Draft PR for now. I can't tell if it's all necessary for something like this that only changes sample code that's not (I guess?) being tested and/or validated.

Fix wrong close tag in code samples for `uui-color-swatch` element

---

packages/uui-menu-item/lib/uui-menu-item.element.ts

Fixes https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1912
Fixes an issue where actions would overflow the menu-item, causing layout problems in the containing element.

fix: prevent overflow when not hovered

---

packages/uui-form-validation-message/lib/uui-form-validation-message.element.ts

Prints the HTML tags inside validation messages.
Fixes https://github.com/umbraco/Umbraco-CMS/issues/16504

fix(uui-form-validation-message): default renderer does not support raw HTML

---

packages/uui-card-block-type/lib/uui-card-block-type.element.ts

Adds missing documentation for slots on the uui-card-block-type element.

docs(uui-card-block-type): add descriptions for slots

---

packages/uui-select/lib/uui-select.element.ts
packages/uui-select/lib/uui-select.story.ts

This PR adds a `readonly` state for the `uui-select` component. It will render the selected value as a text string instead of the select box.

Feat: Readonly state for uui-select

---

packages/uui-slider/lib/uui-slider.element.ts
packages/uui-slider/lib/uui-slider.story.ts

This PR adds a `readonly` state for the `uui-slider` component. It will ensure that the value is always displayed in the slider and that the handle can't be dragged.

Feat: Readonly state for uui-slider

---

packages/uui-boolean-input/lib/uui-boolean-input.element.ts
packages/uui-checkbox/lib/uui-checkbox.element.ts
packages/uui-checkbox/lib/uui-checkbox.story.ts
packages/uui-toggle/lib/uui-toggle.element.ts
packages/uui-toggle/lib/uui-toggle.story.ts

This PR adds a `readonly` state for boolean components. It implements the `readonly` state for checkbox and toggle.

Feat: Readonly state for boolean inputs (Checkbox & Toggle)

---

packages/uui-toggle/lib/uui-toggle.element.ts

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/16697
Prevent UUIToggle from shrinking when the label contains a long string

bug: Prevent UUIToggle from shrinking when the label contains a long string

---

packages/uui-select/lib/uui-select.element.ts

Add CSS variables to the `uui-select` background and text colors to make it work with theming.
Also adds following overrides:
`--uui-select-background-color`
`--uui-select-text-color`

bug(uui-select): Use css vars for background and text color

---

packages/uui-input-lock/lib/index.ts

fix(uui-input-lock): the `UUIInputLockEvent` is not exported

---

packages/uui-file-dropzone/lib/UUIFileDropzoneEvent.ts
packages/uui-file-dropzone/lib/uui-file-dropzone.element.ts
packages/uui-file-dropzone/lib/uui-file-dropzone.test.ts

Dropzone now supports folder uploading. Folders inside folders are also allowed.

feat: dropzone should support folder upload

---

packages/uui-color-picker/lib/uui-color-picker.element.ts
packages/uui-color-picker/lib/uui-color-picker.story.ts

Allows the UUI Color picker to have an empty string as value. This shows up as fully transparent.
Deleting a picked color now sets the value to empty string.
Fixed an issue where when typing in a color manually in the input field it would not update the value.
We dont want the color picker to automatically pick a color for us.

feat(uui-color-picker): allow the value to be empty

---

packages/uui-base/lib/mixins/LabelMixin.ts
packages/uui-button/lib/uui-button.story.ts
packages/uui-button/lib/uui-button.test.ts
packages/uui-toggle/lib/uui-toggle.story.ts

Due to the nature of how the default slot is used in various elements, the extended calculation to check if the default slot is empty or not is faulty. This effectively reverts #844.

fix: revert the function to calculate if a default slot is empty

---

packages/uui-file-dropzone/lib/uui-file-dropzone.element.ts
packages/uui-file-dropzone/lib/uui-file-dropzone.story.ts
packages/uui-file-dropzone/lib/uui-file-dropzone.test.ts

Fixes a bug where the dispatch event was sent before all files were being read (in case of 100+ files)
Dropzone does not accept folder uploads, if the multiple property is set to `false`.
Fixes a bug where the `accept` attribute did not work properly with mimetypes.
Added a story for disallowing folder uploads

bug(uui-file-dropzone): change event is dispatched too early with more than 100 files

---

packages/uui-boolean-input/lib/uui-boolean-input.element.ts
packages/uui-checkbox/lib/uui-checkbox.story.ts
packages/uui-checkbox/lib/uui-checkbox.test.ts
packages/uui-radio/lib/uui-radio-group.test.ts
packages/uui-radio/lib/uui-radio.element.ts
packages/uui-radio/lib/uui-radio.story.ts
packages/uui-toggle/lib/uui-toggle.story.ts
packages/uui-toggle/lib/uui-toggle.test.ts

This PR makes some consistency in cursor style of `<uui-checkbox>` and `<uui-radio>`.
- When `readonly` the text isn't selectable as the the other states
- When `disabled` is use `not-allowed` cursor style instead - the style on `<label>` wasn't consistent for checkbox/radiobutton.
- It had redundant `display` CSS property in  `<uui-radio>`
- Simplified checkbox story using `gap: 20px` instead of `margin-left: 20px` on each item.
I also replaced some of the deprecated `Story` with new `StoryFn` and updated the describe name to same format as `UUIInputFileElement`, so instead of `UuiToggle` -> `UUIToggle` (and before checkbox used same name as toggle in tests)

Consistent cursor style for checkbox and radiobutton

---

packages/uui-loader-bar/lib/uui-loader-bar.element.ts

We now have a generic `clamp` function, so use that instead of defining it locally.
Ref https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1021#issuecomment-2118387247

chore(uui-loader-bar): use the generic `clamp` function from `uui-base`

---

packages/uui-textarea/lib/uui-textarea.element.ts

Show a danger border if the element is invalid. This aligns the element with uui-input.

fix(uui-textarea): add danger border if the element is invalid

---

packages/uui-menu-item/lib/uui-menu-item.element.ts
packages/uui-menu-item/lib/uui-menu-item.story.ts
packages/uui-menu-item/lib/uui-menu-item.test.ts

Tested with Storybook and WTR: The accessibility tests were failing because of a missing aria-label.
This is a prerequisite to fix this CMS issue: https://github.com/umbraco/Umbraco-CMS/issues/16690
1. Try and run the Storybook accessibility tests without a label and then with
2. Try and run the unit tests without a label and then with

fix(uui-menu-item): the caret button is missing an `aria-label` attribute

---

packages/uui-modal/lib/uui-modal-sidebar.element.ts

fixes https://github.com/umbraco/Umbraco-CMS/issues/16844

correct small size to 500px

---

packages/uui-symbol-more/lib/uui-symbol-more.element.ts

This fixes the alignment of the more icon so it's aligned similarly to other icons.
This is the changes applied to the Umbraco backoffice (v14) via devtools:
I've tried to match the icon to a pixel-perfect similar svg icon (See screenshots)
This also fixes the small difference in size of the more icon compared to the other icons
It hurts my eyes that the three dots are not aligned with the other icons 😅 
From storybook (zoomed in a lot):

fix: Aligned more symbol to center

---

packages/uui-caret/lib/uui-caret.element.ts
packages/uui-symbol-expand/lib/uui-symbol-expand.element.ts
packages/uui-symbol-sort/lib/uui-symbol-sort.element.ts
packages/uui-table/lib/uui-table.story.ts

Update style to match new icon style

Update style of expand and sort symbol

---

packages/uui-file-dropzone/lib/uui-file-dropzone.element.ts
packages/uui-file-dropzone/lib/uui-file-dropzone.test.ts

Fixes a bug where uploading a `.udt` file results in error as the dropzone thinks its a folder.

Bugfix: Dropzone thinks custom file extensions are folders

---

packages/uui-slider/lib/uui-slider.element.ts

Fixes https://github.com/umbraco/Umbraco.UI/issues/878 by focusing slider handle instead of slider track itself (although native slider input does this), which also makes it more consistent with `uui-range-slider` https://uui.umbraco.com/?path=/docs/uui-range-slider--docs

Focus handle in slider instead of slider track itself

---

packages/uui-combobox/lib/uui-combobox.element.ts

Fixes: https://github.com/umbraco/Umbraco.UI/issues/748
Fixes combobox dropdown having 0 height in safari.

Bugfix: Combobox not working in Safari

---

packages/uui-color-slider/lib/uui-color-slider.element.ts
packages/uui-color-slider/lib/uui-color-slider.story.ts

This PR adds a readonly state for the `uui-color-slider` component. It will ensure that the handle can't be dragged or slider selected via touch/click event.
Fixes https://github.com/umbraco/Umbraco.UI/issues/899

Feat: Readonly state for uui-color-slider

---

packages/uui-base/lib/mixins/FormControlMixin.ts

Having setAttribute in the constructor is no longer allowed and causes some components in New Backoffice to throw errors and not render.
This fixes it by setting the property instead.

Bugfix: UUIFormControlMixinClass: Dont call setAttribute in the constructor

---

packages/uui-color-swatches/lib/uui-color-swatches.element.ts
packages/uui-color-swatches/lib/uui-color-swatches.story.ts

This PR adds a readonly state for the `uui-color-swatches` component. It will ensure that each swatch can't be selected.
Fixes https://github.com/umbraco/Umbraco.UI/issues/901

Feat: Readonly state for uui-color-swatches

---

packages/uui-color-picker/lib/uui-color-picker.element.ts
packages/uui-color-picker/lib/uui-color-picker.story.ts

This PR adds a readonly state for the `uui-color-picker` component. It will ensure that each sub component can't be selected.
Fixes https://github.com/umbraco/Umbraco.UI/issues/898
Since `uui-button` (and button element in general) doesn't have a readonly mode, I think it makes most sense to select eyedropper button to disabled - alternative return in event, but may be odd nothing happens clicking the button.
I think it is fine the toggle button is active to switch between color format.
Depends on review of https://github.com/umbraco/Umbraco.UI/pull/932

Feat: Readonly state for uui-color-picker

---

packages/uui-range-slider/lib/uui-range-slider.element.ts

The step dots wasn't quite vertically centered on the track as height is 3px and dots where moved 5px.
I added some adjustments, so this is calculated based on height set.
**Before**
**After**

Ensure track step dots are in center on track

---

packages/uui-ref/lib/uui-ref.element.ts

Make actions container visible on focus-within
The change in the PR makes the `#actions-container` element visible when focusing on an element within. Addresses the following issues
- https://github.com/umbraco/Umbraco.UI/issues/947
- https://github.com/umbraco/Umbraco-CMS/issues/17451
Improves accessibility
Navigate to the Node element and use the `Tab` key to make the hidden actions visible on focus.

Make actions container visible on focus-within

---

packages/uui-button/lib/uui-button.element.ts

improve button state explanation

---

packages/uui-checkbox/lib/uui-checkbox.story.ts
packages/uui-radio/lib/uui-radio.story.ts

Fixes some incorrect args in checkbox and radiobutton stories. I also added stories for `disabled` and `readonly` with checked state.
I think in disabled and checked state isn't very clear it is selected (e.g. in TipTap configuration, perhaps use the purple fill and when not disabled - but dimmed?
Current: 
Suggestion:

Fix disabled and readonly checkbox/radiobutton stories

---

packages/uui-color-swatches/lib/uui-color-swatches.story.ts

Minor change to use `color` control for value property instead of raw `string` value.
Not sure why all color swatches were reduced to only three colors. I think the larger amount of swatches showed how it work with many colors and wrap on several lines depending on the container width.
Ideally the stories should cover each state of a component and I think some mock data close to real use-cases is preferable.

Use color control for preselected value in color swatches

---

packages/uui-input/lib/uui-input.element.ts

Make the control part of the uui-input flex-grow.
This will fix case where the input is set to min-width and the content of the input is not that wide, leaving some space that cannot be interacted with. — this change makes the input-element fill all the way, but still leaving room for event append or prepend slotted items.

Fix: Input: set to flex grow

---

packages/uui-range-slider/lib/uui-range-slider.element.ts
packages/uui-slider/lib/uui-slider.element.ts
packages/uui-slider/lib/uui-slider.story.ts

I'm a backend dev, likely, this solution is likely not optimal, feel free to make whatever change you see fit 😄 
As reported over on the CMS tracker the sliders didn't handle decimal values https://github.com/umbraco/Umbraco-CMS/issues/17546 
This PR fixes this.
The fix is to "count" the amount of decimals in the step. I.E `0.1` has 1 decimal, `0.15` has 2, and then round the value to this amount of digits. 
For the normal slider I round the numbers when they're generated, this is because in the render methods the step size is not available. 
For the range slider the rounding happens in the render methods because the step size is available there. 
It doesn't work, see the linked issue
I've added 2 stories to test, if you add these before this change you see weird behaviour.
See issue

Fix: Make slider handle decimal values

---

packages/uui-boolean-input/lib/uui-boolean-input.element.ts
packages/uui-boolean-input/lib/uui-boolean-input.test.ts
packages/uui-input/lib/uui-input.element.ts
packages/uui-input/lib/uui-input.test.ts
packages/uui-range-slider/lib/uui-range-slider.element.ts
packages/uui-range-slider/lib/uui-range-slider.test.ts
packages/uui-slider/lib/uui-slider.element.ts
packages/uui-slider/lib/uui-slider.test.ts

Stop using keypress.
See: https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event

Feat: stop using keypress

---

packages/uui-icon/lib/uui-icon.element.ts
packages/uui-menu-item/lib/uui-menu-item.element.ts
packages/uui-symbol-expand/lib/uui-symbol-expand.element.ts

One of the things that really hurts my eyes when looking at the new backoffice, is that things feel off and misaligned. So I dug a bit in the menu item component and found some improvements.
I moved the caret for displaying children further to the right, to make it visually connect with the menu item. Previously it looked closer to the browser edge (and also vertically unbalanced) than to the menu item itself.
I also added an aspect-ratio to the caret, to make the browser render a square box for it (instead of 12x17 pixels), which made it connect to the baseline of the label text.
I bumped the font-size of the icon to 15.66px, to make it render a 18x18 icon, instead of 18.39x.18.x39 which caused subpixel issues.
You can see a zoomed in before and after here: (after is the left one, note …

Fix alignment of menu-item parts

---

packages/uui-css/lib/uui-text.css

After we allowed `.uui-h*` classes to be used outside a `.uui-text` container it got a lower specifity. I have fixed this so it is still possible to use the styles like previously.
How to test:
* Make sure the `.uui-h*` styles work outside a `.uui-text` container.
* Make sure you can override a `h1`, `h2`, `h3` style inside a `.uui-text` container with a `.uui-h*` class.
* Example `<div class="uui-text"><h1 class="uui-h3">This should have h3 styling</h1></div>`

Fix: double declare uui-h styles to bring back previous specificity

---

packages/uui-base/lib/mixins/SelectableMixin.ts
packages/uui-card-media/lib/uui-card-media.test.ts

A fix to avoid selection happening when clicking or keyboard interacting with sub element of a selectable element.

Fix: do not select when opening href on selectable elements

---

packages/uui-card-media/lib/uui-card-media.element.ts

Problem: It is no longer possible to use the media card actions when a media item has an href:
This PR bumps the z-index for the action and tag slots
* make sure that you can click the actions when a card has en href

fix: bump media card action and tag slot z-index

---

packages/uui-action-bar/lib/uui-action-bar.element.ts

Enable implementors to use their own element wrapping uui-button in the action-bar.

UUI-Action-Bar: target any slotted element

---

packages/uui-base/lib/utils/drag.ts

Fixes issue #1000 
drag does not work on Firefox

Fix reference to TouchEvent which is not defined in Firefox

---

packages/uui-base/lib/utils/drag.ts
packages/uui-tabs/lib/uui-tab-group.element.ts
packages/uui-tabs/lib/uui-tabs.test.ts

Fixes: https://github.com/umbraco/Umbraco.UI/issues/987
When the tab list does not fit into view, the more button was causing an accessibility violation error.
This has been corrected by moving the tablist role to the grid and the popover tablist.
Note this still does not make this component fully accessible, but it does remove the accessibility violation errors. There is another issue (issues/700) that I will address after this fix is applied.
Rather than having the role of tablist on the root of the component, it has been placed on the parts of the dom which directly house the tabs. This has meant requiring two tablists - one for the normal list, and one for the "more" list.
It should be noted that a [previous pull request](https://github.com/umbraco/Umbraco.UI/pull/996) was attempted …

fix: accessibility problem with more button on tablist

---

packages/uui-toggle/lib/uui-toggle.element.ts

Just a minor update renaming `#slider` to `#toggle` (or alternatively `#switch`) to not confuse with the slider editor and as a boolean input doesn't really act as slider (or between 0 and 1 in that case).

Rename id from slider to toggle

---

packages/uui-symbol-expand/lib/uui-symbol-expand.element.ts

Changed display property from inline-block to inline-flex
Fixed vertical alignment by changing css display property from inline-block to inline-flex
It solves vertical alignment of carrot icon against menu item in umbraco backoffice tree menu
After:
Before:

Fix vertical alignment uui-symbol-expand.element.ts

---

packages/uui-ref-node/lib/uui-ref-node.element.ts

When adjusting the margin for ref items without an open part, I didn't notice that we had this extra margin when selected. This margin can be removed now because it results in a "double" margin.

Fix: Remove extra margin on ref-node

---

packages/uui-card-media/lib/uui-card-media.element.ts

This PR fixes issue https://github.com/umbraco/Umbraco.UI/issues/865
The media card name will display with an ellipsis at the end if the name is too long. Hover to the name to see the full text.
Before:
After fix:

Fix bug long media name hides the thumbnail

---

packages/uui-icon/lib/uui-icon.element.ts

Center aligns icon in textual context.
So icons align alright like here:

vertical center align icon when used in text

---

storyhelpers/render-slots.ts

This makes the stories that uses `renderSlots()` work again.

fix: ensure `renderSlots()` return correctly tagged unsafe html

---

packages/uui-color-area/lib/uui-color-area.element.ts

fixes the color-picker-handles placement, after selecting a preset value
Due to missing saturation, the placement of the color-picker-handle would also default to 0 or to the last x axel position.
Cleaning up the UI
Open a color-picker and select any of the prevalues, and see that color-picker move

fixes the color-picker-handles placement, after selecting a preset value

---

packages/uui-ref-node/lib/uui-ref-node.element.ts

Fixes https://github.com/umbraco/Umbraco.UI/issues/983

fix: 'uui-ref' spacing is different when readonly is enabled

---

packages/uui-label/lib/uui-label.element.ts

We changed this recent to follow along with the invalid color, but it is not ideal for the asterix to follow this, so reverting this part.

UUI-Label: always red asterix

---

packages/uui-base/lib/utils/drag.ts

Fixes regression made in PR https://github.com/umbraco/Umbraco.UI/pull/1001 and metioned here: https://github.com/umbraco/Umbraco.UI/pull/1001#issuecomment-2816816476
Noticed in Chrome Version 135.0.7049.96 / Win 10 Pro.
In Chrome the click event returns `MouseEvent`, so it went to `else` statement and stopped executing the `onMove()` event.
It may be a bug that Firefox return `PointerEvent` as click is a `MouseEvent`:
https://stackoverflow.com/a/76900433
I can reproduce to issue in Firefox as well, so it may only be an issue click returning `PointerEvent` in older versions of Firefox and Safari as these has been resolved:
https://bugzilla.mozilla.org/show_bug.cgi?id=1675847
https://bugs.webkit.org/show_bug.cgi?id=218665
However it is safe casting to `MouseEvent` as `PointerEvent` …

Fix selection on click in color area

---

packages/uui-input-lock/lib/uui-input-lock.element.ts
packages/uui-input/lib/uui-input.element.ts

Implements the tabIndex for input and makes use of that for the uui-input-lock, so the user does not focus on the input when it is locked.
As well when unlocking we now focus the input and implemented options to define the label for lock-button and unluck-button

uui-input-lock: Only focus input when unlocked

---

packages/uui-base/lib/mixins/LabelMixin.ts
packages/uui-boolean-input/lib/uui-boolean-input.element.ts
packages/uui-input/lib/uui-input.element.ts
packages/uui-input/lib/uui-input.story.ts
packages/uui-ref-node/lib/uui-ref-node.element.ts
packages/uui-ref/lib/uui-ref.element.ts
packages/uui-table/lib/uui-table-advanced-example.ts

Fixing the vertical alignment for icons and related, in inputs and table and ref items.

Fix prepending icons and vertical alignment

---

packages/uui-card-media/lib/uui-card-media.element.ts
packages/uui-card-media/lib/uui-card-media.story.ts

In the `<uui-card-media>` component, sets `#content` to use `flex-direction: column`, so that the `detail` will display below the `name`.

Fix: `uui-card-media`: flex-direction of "content"

---

packages/uui-base/lib/mixins/LabelMixin.ts

I have seen a few issues where we get this warning despite a label being set. A bit like if this was executed just before it got set, so this should be better.

use firstUpdated for label feedback

---

packages/uui-button/lib/uui-button.element.ts

Bug fix for - https://github.com/umbraco/Umbraco.UI/issues/1054
Add the attr to the HTML Button and consume the type prop value for it.
Stop weired behavior where all form are kind of submitted even tho it is just a button
Storybook, try to set it to submit and i devtool see the button type become "SUBMIT"

Add support type attr. on button

---

packages/uui-input/lib/uui-input.element.ts

Fix vertical alignment of input text caused by padding inconsistency.
The green color indicates the padding size
**Before**
**After**
**Before**
**After**

Fix vertical alignment of input text for uui-input.element.ts

---

packages/uui-combobox/lib/uui-combobox.element.ts

When inspecting the `uui-combobox` element, there is some form of whitespace/padding/gap at the bottom of the component.
Inspecting the element and shadow DOM, I haven't been able to locate the cause of the gap.
I did find that changing the `display` from `inline-block` to `inline-flex` appears to resolve the gap issue.
In Umbraco CMS, there are features that need to flexbox align components next to the combobox, but the additional gapping at the bottom causes them to appear misaligned (by a few pixels).
Using the browser's devtools, inspect the combobox element, notice if the bottom gap has gone.

fix(uui-combobox): Remove bottom gap

---

packages/uui-color-picker/lib/uui-color-picker.element.ts
packages/uui-color-picker/lib/uui-color-picker.story.ts
packages/uui-color-slider/lib/uui-color-slider.element.ts
packages/uui-color-slider/lib/uui-color-slider.story.ts

In the UUI Color Picker component, sets the preview colour of an empty value to transparent.
In PR #1061, the change set the `alpha` to `100` for undefined values, this meant that all empty values would now appear as black (`#000000`), but the value would remain as empty.
Prior to this change, the initial preview colour for empty values was transparent. This PR updates the preview colour accordingly.
In the storybook for the Color Picker component, view the Empty story, notice that the button has a transparent background colour.

fix(uui-color-picker): sets preview color of empty value to transparent

---

packages/uui-color-picker/lib/uui-color-picker.element.ts
packages/uui-color-slider/lib/uui-color-slider.element.ts
packages/uui-color-slider/lib/uui-color-slider.story.ts

Adds a `hide-value-label` option to the UUI Color Slider component.
The reason for this is when used in the UUI Color Picker inline/popover component, the Hue slider has a numeric value beneath it, ranging from 0 to 360. This value holds little relevance to the UX or the specified colour value. By hiding the value label, the UI is also tightened up a little.
Open the Color Picker component, notice that the numerical value below the Hue slider is not visible.

feat(uui-color-slider): adds `hideValueLabel` option

---

packages/uui-button/lib/uui-button.element.ts
packages/uui-button/lib/uui-button.story.ts

Added a focus color property to control the focus state color for further use and more customizability
This helps fix an accessibility issue in the backoffice 
When tabbing through the buttons below the focus state that is coming up does not appear due to the color being the same as the background
Run the project and go to the button section and change the new property `--uui-focus-outline-color`

feature-upgrade/button - Focus state color can be controled

---

packages/uui-menu-item/lib/uui-menu-item.element.ts
packages/uui-menu-item/lib/uui-menu-item.story.ts

Adds ability to bring a custom render/template for the Expand-button insides/symbol — We need this in the CMS for the Collections-shortcut.

uui-menu-item: custom expand symbol render method
